max_records: 1000

security_policies:
  disallowed_operations:
    - INSERT
    - UPDATE
    - DELETE
    - DROP
    - ALTER
    - TRUNCATE
    - CREATE
    - GRANT
    - REVOKE
    - EXECUTE
  
  injection_patterns:
    - "';--"
    - "' OR '1'='1"
    - "' OR 1=1"
    - "1=1"
    - "UNION SELECT"
    - "EXEC("
    - "EXECUTE("
    - xp_
    - sp_
    - "/*"
    - "*/"
    - "--"
    - "@@"
  
  prompt_injection_patterns:
    - "ignore previous"
    - "ignore all previous"
    - "disregard previous"
    - "forget previous"
    - "new instructions"
    - "system prompt"
    - "you are now"
    - "act as if"

intent_policies:
  require_explicit:
    - table_name
    - filter_conditions
  
  disallowed_intents:
    - modify_data
    - delete_data
    - create_schema
    - drop_schema
    - access_credentials
    - export_full_table

validation_rules:
  min_query_length: 5
  max_query_length: 500
  require_context: true